# Generated by Django 3.2.6 on 2021-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_topic_topic_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_body',
            field=models.CharField(max_length=1000, verbose_name='回复'),
        ),
    ]
