# Generated by Django 3.2.6 on 2021-09-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_remove_wallet_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='public_key',
            new_name='publickey',
        ),
    ]
