# Generated by Django 3.2.6 on 2021-08-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstage',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, '未定义'), (1, '时间'), (2, '地点'), (3, '人物'), (4, '事件'), (5, '概念')], default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '删除'), (1, '正常'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, '未定义'), (1, '时间'), (2, '地点'), (3, '人物'), (4, '事件'), (5, '概念')], default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '删除'), (1, '正常'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
    ]
