# Generated by Django 3.2.6 on 2021-08-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20210824_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstage',
            old_name='kind',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='kind',
            new_name='type',
        ),
    ]
