# Generated by Django 3.2.6 on 2021-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20210825_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(blank=True, verbose_name='次序'),
        ),
        migrations.AlterField(
            model_name='historicalchapter',
            name='order',
            field=models.IntegerField(blank=True, verbose_name='次序'),
        ),
    ]
