# Generated by Django 3.2.6 on 2021-08-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20210825_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='次序'),
        ),
        migrations.AlterField(
            model_name='historicalchapter',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='次序'),
        ),
    ]
