# Generated by Django 3.2.6 on 2021-08-25 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0007_auto_20210825_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='故事章节')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(verbose_name='情节内容')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='次序')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='修改时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('belong_to_story', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='works.story', verbose_name='所属故事')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': 'historical plot',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='故事章节')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(verbose_name='情节内容')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='次序')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('belong_to_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.story', verbose_name='所属故事')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='belong_to_story',
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='belong_to_chapter',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='belong_to_chapter',
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='content',
            field=django_editorjs_fields.fields.EditorJsJSONField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='content',
            field=django_editorjs_fields.fields.EditorJsJSONField(verbose_name='内容'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='HistoricalChapter',
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='belong_to_plot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='works.plot', verbose_name='所属情节'),
        ),
        migrations.AddField(
            model_name='stage',
            name='belong_to_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='works.plot', verbose_name='所属情节'),
        ),
    ]
