# Generated by Django 3.2.6 on 2021-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20210929_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstage',
            name='maturity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='成熟度'),
        ),
        migrations.AddField(
            model_name='stage',
            name='maturity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='成熟度'),
        ),
    ]
