# Generated by Django 3.2.6 on 2021-10-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20211001_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstage',
            name='openess',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('SEMI_PUBLIC', 'SemiPublic'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AddField(
            model_name='stage',
            name='openess',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('SEMI_PUBLIC', 'SemiPublic'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
    ]
