# Generated by Django 3.2.6 on 2021-10-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0013_auto_20211001_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstage',
            name='words_count',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
        migrations.AddField(
            model_name='stage',
            name='words_count',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
    ]
