# Generated by Django 3.2.6 on 2021-10-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_auto_20211007_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstage',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级')], default=1, verbose_name='评级'),
        ),
        migrations.AddField(
            model_name='stage',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级')], default=1, verbose_name='评级'),
        ),
        migrations.AlterField(
            model_name='historicalstage',
            name='openess',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('SEMI_PUBLIC', 'SemiPublic'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20, verbose_name='开放性'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='openess',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('SEMI_PUBLIC', 'SemiPublic'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20, verbose_name='开放性'),
        ),
    ]
