# Generated by Django 3.2.6 on 2021-10-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20211008_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstage',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='星'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='星'),
        ),
    ]
