# Generated by Django 3.2.6 on 2021-09-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='account_id',
        ),
    ]
