# Generated by Django 3.2.6 on 2021-10-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usernname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
