# Generated by Django 3.2.6 on 2021-10-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_wallet_usernname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='usernname',
            new_name='username',
        ),
    ]
