# Generated by Django 3.2.6 on 2021-10-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_rename_usernname_wallet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
