# Generated by Django 3.2.6 on 2021-08-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
